### ISSUE TITLE
persistent storage (pvc) for templates

### ISSUE THREAD

**Issue by patredtheknight** [bcgov/common-document-generation-service#87] opened 2022-07-07 13:07 UTC
Hi 
I'd like to know if it is possible to put the templates on a persistent volume. Now every time the pod(s) restart all the templates disappear from the cache directory (tmp/carbone-files)
We would like to keep the templates (and maybe even the rendered files) on an AWS pvc

Is there such a config variable?

Thank you

**Comment by jujaga** [comment] 2022-07-07 20:29
Hi @patredtheknight there should already be a PersistentVolumeClaim definition in `app.dc.yaml` which would ensure that you had persistent storage for your cached templates. https://github.com/bcgov/common-document-generation-service/blob/b0995ba89b8b4501963c2db8297fe9b741118c8f/openshift/app.dc.yaml#L182-L194

**Comment by patredtheknight** [comment] 2022-07-08 12:00
Hi [Jujaga](https://github.com/jujaga)
Thank you for the quick reply
we have a bit of a different setup (no open shift but AWS) and use a similar claim (without the variables though)

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-carbone-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
`

and volume
`---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-carbone
  namespace: default
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-378dd608:/opt/app-root/carbone-files
`

and all looks well and healthy

![image](https://user-images.githubusercontent.com/46375863/177987597-ab06e9fb-9089-477a-aa62-56233f144e2d.png)

Still if the pod restarts, the templates are gone
Any ideas?

Patred

**Comment by jujaga** [comment] 2022-07-08 16:37
If you are not using the openshift templates to standup your instance of CDOGS, the best I can recommend to you is to comb through the `app.dc.yaml` file as a reference and make sure that your equivalent `FILE_CACHE_DIR` and PVC volume mount location aligns with where the application is writing the templates to. If you are writing template files to a directory different than the one you have mounted your PVC onto, they obviously will not show up across container restarts as you would have been writing the templates to an ephemeral directory.

Reference the following lines in the `app.dc.yaml` template to guide your k8s template debugging efforts:
https://github.com/bcgov/common-document-generation-service/blob/b0995ba89b8b4501963c2db8297fe9b741118c8f/openshift/app.dc.yaml#L68-L70
https://github.com/bcgov/common-document-generation-service/blob/b0995ba89b8b4501963c2db8297fe9b741118c8f/openshift/app.dc.yaml#L156-L169

I am closing this issue because this is an external configuration problem where the root cause is not coming from the code nor the openshift templates provided.

**Closed by jujaga** 2022-07-08 16:37 UTC
